Fixes Playing video from asset on Android
flutter/plugins pull request #3123
Opened 2020-10-08 01:52 UTC by ponnamkarthik

## Description

Fixes issue with video_player plugins throws error when playing an asset file on android.

## Related Issues
 
[flutter/flutter#66627](https://github.com/flutter/flutter/issues/66627)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

2020-10-09 14:44 UTC, Ehesp requested changes
LGTM - please can you run `pub global run flutter_plugin_tools format --plugins video_player` (`pub global activate flutter_plugin_tools`).

2020-10-09 14:44 UTC, Ehesp commented
Can confirm this fix works:

![image](https://user-images.githubusercontent.com/842078/95597272-5382c680-0a46-11eb-80b8-ed0303ef50d6.png)

2020-10-13 14:52 UTC, Ehesp commented
@amirh Would you be able to take a look at this one? It's currently blocking https://github.com/flutter/flutter/issues/66627

2020-10-13 14:53 UTC, Ehesp approved these changes

2020-10-13 16:47 UTC, cyanglaz commented
@ponnamkarthik Thanks for the fix! This is great! Can we add tests for this?

2020-10-13 16:47 UTC, cyanglaz commented
I notice that the plugin has another issue that the platform exception reporting is broken. Meaning that the error code is always null, which broke the exception reporting. See https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/Messages.java#L600 This is an automatically generated code by pigeon. @gaaclarke do you think we can fix it from pigeon? Or we should just manually fix it for the plugin too?

2020-10-13 17:02 UTC, gaaclarke commented
> I notice that the plugin has another issue that the platform exception reporting is broken. Meaning that the error code is always null, which broke the exception reporting. See https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/Messages.java#L600 This is an automatically generated code by pigeon. @gaaclarke do you think we can fix it from pigeon? Or we should just manually fix it for the plugin too?

We have an issue related to this already here: https://github.com/flutter/flutter/issues/67586  If you could fix it in pigeon that would be helpful.  I'll get around to it eventually.  Any manual fix will probably get overwritten on accident.

2020-10-13 23:52 UTC, gaaclarke commented
@cyanglaz I've landed an external contributors fix for this: https://github.com/flutter/flutter/issues/67586  It will publish in 0.1.12 if you can LGTM my PR https://github.com/flutter/packages/pull/224

2020-10-15 18:10 UTC, cyanglaz commented
@ponnamkarthik looks like this PR is missing tests, could you add tests before we can land it?

2020-10-15 20:18 UTC, Ehesp commented
@cyanglaz The current tests suggest that it isn't possible: https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/example/test_driver/video_player_test.dart#L15

Can you advise on what's needed to test this PR? Without it working on an emulator I'm not sure what can be done.

2020-10-20 16:12 UTC, xster approved these changes
This is the correct fix. 

https://github.com/flutter/plugins/pull/3072 didn't refactor correctly to match https://github.com/flutter/engine/pull/20789. LGTM.

2020-10-20 16:12 UTC, xster commented on packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java
> +
remove extra line

2020-10-20 19:49 UTC, cyanglaz commented
@Ehesp For testing, is it possible to repro the exception with a test like https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/example/integration_test/video_player_test.dart#L32-L41? I also wonder why this particular test didn't fail because of this bug. Looking at the issue description, I felt the test should throw the same exception as it is loading a video from assets.

2020-10-21 09:19 UTC, Ehesp commented
Yeah I'm not sure either. I'll have to investigate it more.

2020-10-27 09:40 UTC, OmerDital commented
@ponnamkarthik Thanks for the fix!!

2020-10-28 20:51 UTC, merged

2020-12-28 20:02 UTC, Lix-ai commented
Issue still exists...
Seen using BLoC states.


E/flutter ( 2690): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/services/message_codec.dart': Failed assertion: line 111 pos 15: 'code != null': is not true.
E/flutter ( 2690): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter ( 2690): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 2690): #2      new PlatformException (package:flutter/src/services/message_codec.dart:111:15)
E/flutter ( 2690): #3      VideoPlayerApi.create (package:video_player_platform_interface/messages.dart:205:13)
E/flutter ( 2690): <asynchronous suspension>