[url_launcher] Handling the ActivityNotFoundExeption.
flutter/plugins pull request #3125
Opened 2020-10-08 11:09 UTC by Sempakonka

## Description

Currently on android when you call the `launch` method with an URL of wich there isn't any app installed that can open this URL,  nothing happens. This is because the method that launches the app throws an exception when this occurs, but the exception is never handled. In this PR it adds the handling of this exception.

It adds a new `ACTIVITY_NOT_FOUND` LaunchStatus. When the `launch` method returns this, a new error state will be returned. This will inform the developer wich URL the device does not have any app for.

## Related Issues

[Issue 66826](https://github.com/flutter/flutter/issues/66826)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2020-10-08 14:39 UTC, Sempakonka commented
@googlebot I consent.

2020-10-08 14:40 UTC, mvanbeusekom commented
@googlebot I consent.

2020-10-14 21:37 UTC, amirh requested changes
Missing a test

2020-10-14 21:37 UTC, amirh commented on packages/url_launcher/url_launcher/CHANGELOG.md
> +* Added a new `LaunchStatus` to handle the ActivityNotFound exception that `activity.startActivity` can throw.
nit: Let's make this message about what have changed from the plugin's user perspective. e.g maybe something like: "Fixed a crash on Android when there is no activity to handle the URL intent, instead the launch method will now throw a Dart PlatformException." (assuming I got the consequences right, side note: would be helpful to describe the previous bad behavior and the new behavior in the PR description)

2020-10-21 04:12 UTC, amirh approved these changes
LGTM

2020-10-22 17:05 UTC, amirh commented
Will land on green

2020-10-23 16:36 UTC, merged