[camera] Added information of video not working correctly on Android emulators…
flutter/plugins pull request #3180
Opened 2020-10-21 14:02 UTC by valconetti

… to `README.md`.

## Description

To make sure no developers try to find out why the a video with audio on an Android emulator isn't working properly, I added it to the README.md.

## Related Issues

[Issue 42309](https://github.com/flutter/flutter/issues/42309#)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2020-10-21 18:03 UTC, mvanbeusekom requested changes

2020-10-21 18:03 UTC, mvanbeusekom commented on packages/camera/README.md
> +see the first frame.
Can you also include the link to the official article which confirms recording video on the Android emulator is not working correctly?

Also a small suggestion on improving the text:
```suggestion
Important to note is that the `MediaRecorder` class is not working properly on emulators. Specifically when recording a video with sound enabled and try to play it back, the duration won't be correct and you will only
see the first frame.
```

2020-10-23 18:09 UTC, bparrishMines approved these changes
LGTM with small nit

2020-10-23 18:09 UTC, bparrishMines commented on packages/camera/README.md
> +Important to note is that the `MediaRecorder` class is not working properly on emulators, as stated in the documentation: https://developer.android.com/reference/android/media/MediaRecorder. Specific
nit:

```suggestion
It's important to note that the `MediaRecorder` class is not working properly on emulators, as stated in the documentation: https://developer.android.com/reference/android/media/MediaRecorder. Specifically, when recording a video with sound enabled and trying to play it back, the duration won't be correct and you will only see the first frame.
```

2020-10-24 09:14 UTC, mvanbeusekom approved these changes

2020-10-28 17:24 UTC, merged