[cross_file] An abstraction to allow working with files across multiple platforms.
flutter/plugins pull request #3260
Opened 2020-11-10 11:05 UTC by mvanbeusekom

## Description

This PR copies the [x_file](https://github.com/flutter/plugins/tree/master/packages/file_selector/file_selector_platform_interface/lib/src/types/x_file) types from the [file_selector](https://github.com/flutter/plugins/tree/master/packages/file_selector) package into it's own package. This will allow us to easily reuse this cross platform file abstraction in other plugins that are dealing with files, without having to duplicate the code.

At the moment there is a requirement to use these types also in the [camera](https://github.com/flutter/plugins/tree/master/packages/camera) plugin so it would be easier to add a web implementation (suggestion to use x_file originated from @ditman, see [here](https://github.com/flutter/plugins/pull/3253#discussion_r519067323)). Additional interest has been shown to use it in the [image_picker](https://github.com/flutter/plugins/tree/master/packages/image_picker) plugin and [cache_manager](https://github.com/baseflow/flutter_cache_manager) package.

Note: I took the liberty of renaming `XFile` to `CrossFile` since a package with the name "XFile" already exists on pub.dev but with a different purpose.

If this PR is accepted and the package is published, I will make sure to also migrate the file_selector plugin to this new package.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2020-11-10 19:54 UTC, ditman requested changes
Is there a way that we can preserve @jasonpanelli's authorship on this package? Can we maybe add him as a co-author of one of your commits, and then ensure that when we merge he stays as a co-author?

Thanks!

2020-11-10 19:54 UTC, ditman commented on packages/cross_file/lib/src/web_helpers/web_helpers.dart
> +import 'dart:html';
This file is missing the copyright notice, can you add it?

2020-11-10 19:54 UTC, ditman commented on packages/cross_file/lib/src/types/io.dart
> +import 'dart:convert';
This file is missing the copyright notice, can you add it?

2020-11-10 19:54 UTC, ditman commented on packages/cross_file/lib/src/types/interface.dart
> +import 'dart:typed_data';
This file is missing the copyright notice, can you add it?

2020-11-10 19:54 UTC, ditman commented on packages/cross_file/lib/src/types/html.dart
> +import 'dart:convert';
This file is missing the copyright notice, can you add it?

2020-11-10 19:54 UTC, ditman commented on packages/cross_file/lib/src/types/base.dart
> +import 'dart:convert';
This file is missing the copyright notice, can you add it?

2020-11-10 19:54 UTC, ditman commented on packages/cross_file/lib/src/cross_file.dart
> +export 'types/interface.dart'
This file is missing the copyright notice, can you add it?

2020-11-10 19:54 UTC, ditman commented on packages/cross_file/lib/cross_file.dart
> +export 'src/cross_file.dart';
This file is missing the copyright notice, can you add it?

2020-11-10 20:24 UTC, mvanbeusekom commented
@googlebot I consent.

2020-11-10 20:32 UTC, mvanbeusekom commented
@ditman thanks for the review. I have added the missing copyrights and immediately added @jasonpanelli as co-author. This however resulted in the CLA step failing since Jason now needs to also give his consent (which makes sense, but didn't think about it earlier).

Also I did a `git mv` when copying all files from the file_selector plugin, so if one would run for example `git log --follow packages/cross-file/lib/src/types/base.dart` you can still see the full history including all commits by @jasonpanelli.

2020-11-10 22:59 UTC, ditman commented
Thanks for the extra effort @mvanbeusekom!

@jasonpanelli, when you have time, can you please tell googlebot you consent to this change? Thanks!

2020-11-10 23:00 UTC, ditman commented
/cc @tugorez can you please also take a look at the new CrossFile, and see if it fits future usages or the ability to add extra metadata? Thanks!!

2020-11-12 00:08 UTC, ditman commented
Quick note @mvanbeusekom: there's already some implementations coming for the file_selector plugin [example](https://github.com/flutter/plugins/pull/3265).

I understand that the package name conflicts with something already in pub, and I think CrossFile is a good name for it; but could we maintain the name of the class that this package exports as `XFile`, so we can introduce the new package through the `platform_interface` in a backwards-compatible way?

_(If we decide to go through with naming the class `CrossFile`, we'd need to bump the major version of the platform_interface package interface to introduce the new class name)_

2020-11-12 12:40 UTC, mvanbeusekom commented
> Quick note @mvanbeusekom: there's already some implementations coming for the file_selector plugin [example](https://github.com/flutter/plugins/pull/3265).
> 
> I understand that the package name conflicts with something already in pub, and I think CrossFile is a good name for it; but could we maintain the name of the class that this package exports as `XFile`, so we can introduce the new package through the `platform_interface` in a backwards-compatible way?
> 
> _(If we decide to go through with naming the class `CrossFile`, we'd need to bump the major version of the platform_interface package interface to introduce the new class name; this bump cascades to the implementations as well, because those would have an implementation that return an XFile, which then gets migrated to CrossFile)_

This is a good point. I have renamed the classes (and file names) back to `XFile` while keeping the package name `CrossFile`.

2020-11-12 19:02 UTC, ditman commented
(I've pinged @jasonpanelli to get his approval!)

2020-11-12 19:40 UTC, jasonpanelli commented
@googlebot I consent.

2020-11-12 20:19 UTC, ditman commented
Ah yes, I forgot to mention this check:

```
* The name of "lib/x_file.dart", "x_file", should match the name of the package, "cross_file".
  This helps users know what library to import.
```

2020-11-12 21:21 UTC, mvanbeusekom commented
> Ah yes, I forgot to mention this check:
> 
> ```
> * The name of "lib/x_file.dart", "x_file", should match the name of the package, "cross_file".
>   This helps users know what library to import.
> ```

Should be fixed now, CI is all green

2020-11-18 02:00 UTC, ditman approved these changes
This is going to be great. If there's any issue with the merge, feel free to add me to the CODEOWNERS for this package!

2020-11-18 08:04 UTC, merged

2020-11-19 22:04 UTC, ditman commented
Note to all: `package: cross_file` is now a thing:

https://pub.dev/packages/cross_file