[camera] Expanded platform interface so support setting flash mode
flutter/plugins pull request #3313
Opened 2020-12-09 08:45 UTC by BeMacized

## Description

Adds the required methods necessary to implement flash support to the camera_platform_interface. Once this PR has landed packages implementing the camera_platform_interface will be able to add flash support to the camera implementations.

## Related Issues

flutter/flutter#19845

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2020-12-09 19:46 UTC, mvanbeusekom approved these changes
LGTM, can be merged when tree goes green

2020-12-09 23:37 UTC, ditman approved these changes
This is great! And it seems to be implementable in web!

My only recommendation is not to rely on the toString method of the FlashMode Enum, and instead have a translation table from enum -> string. Other than that, ship it!

2020-12-09 23:37 UTC, ditman commented on packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart
> +          'mode': mode.toString().split('.').last,
I'd recommend doing a `Map<FlashMode, String>` to do this conversion, instead of relying on the "toString" representation of the Enum.

2020-12-10 08:59 UTC, mvanbeusekom approved these changes
LGTM

2020-12-10 09:02 UTC, mvanbeusekom commented on packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart
> +  }
You should handle the `default` case and throw an argument error explaining the supplied value cannot be supported.

2020-12-10 09:03 UTC, mvanbeusekom requested changes
Left a comment after `flutter analyze` failed.

2020-12-10 09:08 UTC, mvanbeusekom approved these changes

2020-12-10 13:44 UTC, merged