[camera_platform_interface] Add platform interface methods for locking capture orientation.
flutter/plugins pull request #3389
Opened 2021-01-05 15:26 UTC by BeMacized

## Description

Adds the required methods necessary to implement orientation locking to the camera_platform_interface. Once this PR has landed packages implementing the camera_platform_interface will be able to add support for orientation locking to the camera implementations.

It allows for:

- Locking a specific capture orientation
- Locking the current orientation
- Unlocking the capture orientation
- Listening for the current device orientation (Needed to adjust the rotation of the preview widget)

## Related Issues

- flutter/flutter#39071

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2021-01-05 22:06 UTC, mvanbeusekom requested changes
Looks good in general, just some documentation suggestions.

2021-01-05 22:06 UTC, mvanbeusekom commented on packages/camera/camera_platform_interface/lib/src/events/device_event.dart
> +  /// The new orientation the device
nit: grammar mistake (missing the word "of"):

```suggestion
  /// The new orientation of the device
```

2021-01-05 22:06 UTC, mvanbeusekom commented on packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart
> +  /// from handleMethodCall. Specific to camera events.
nit: I think this can be updated to one sentence:

```suggestion
  /// from handleMethodCall, specific to camera events.
```

2021-01-05 22:06 UTC, mvanbeusekom commented on packages/camera/camera_platform_interface/lib/src/method_channel/method_channel_camera.dart
> +  /// from handleMethodCall. Specific to general device events.
nit: can also be updated to one sentence:

```suggestion
  /// from handleMethodCall, specific to general device events.
```

2021-01-06 08:46 UTC, mvanbeusekom commented
@googlebot I consent.

2021-01-06 08:48 UTC, BeMacized commented
@googlebot I consent.

2021-01-06 08:54 UTC, mvanbeusekom approved these changes
LGTM

2021-01-06 22:32 UTC, bparrishMines approved these changes
LGTM

2021-01-07 09:08 UTC, merged