[google_maps_flutter] iOS Pattern Support for Polylines
flutter/plugins pull request #3441
Opened 2021-01-19 11:09 UTC by vanlooverenkoen

Added the iOS implementation for pattern support with polylines.

I have a Java/Kotlin background so this was a real challenge for me. Please update the code if it should be implemented differently. But this is working fine for me. (I don't have experience with tests in iOS so please help me with that)

Updated the example as well

*List which issues are fixed by this PR. You must list at least one issue.*
Fixed: https://github.com/flutter/flutter/issues/60083

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [ ] All existing and new tests are passing.

2021-01-20 11:26 UTC, vanlooverenkoen commented
How do I fix these `This user does not have permission to run Firebase Test Lab tests.` errors?

2021-01-23 09:03 UTC, vanlooverenkoen commented
@ditman can you review this pull request as well?

2021-01-25 22:31 UTC, ditman commented
> How do I fix these This user does not have permission to run Firebase Test Lab tests. errors?

@vanlooverenkoen when was this last rebased with `master`? I haven't seen those errors recently, maybe this branch is missing some config? (@cyanglaz might know more)

2021-01-26 07:12 UTC, vanlooverenkoen commented
Last rebase was on Saturday.

2021-01-26 17:56 UTC, cyanglaz commented
I've never seen this. try re-running

2021-02-23 21:21 UTC, stuartmorgan commented
> I've never seen this. try re-running

It's persistent, I'm trying to figure out why it's happening offline. It doesn't need to block things for now though.

2021-02-23 21:23 UTC, stuartmorgan commented
Thanks for the submission! We’re currently working through a large backlog of PRs, and this will require non-trivial review, so it will take some time before we’re able to review it. As explained in [CONTRIBUTING.md](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#the-review-process), votes for the corresponding issue are the primary way we’re prioritizing non-trivial reviews, so we encourage anyone interested in this PR to vote for the corresponding issue.

2021-03-12 07:50 UTC, vanlooverenkoen commented
@cyanglaz I fixed my pull rewuesy

2021-03-12 08:42 UTC, vanlooverenkoen commented
@cyanglaz & @ditman can you review my pull request. all checks have passed after merging from master.

2021-04-06 22:46 UTC, allanwolski commented
I need this too.

2021-06-18 08:17 UTC, vincepunkrock commented
Please reviewers, review and approve this PR :)

2021-06-21 10:06 UTC, chandaniBhalala commented
Hello, i need dash polyline in iOS also. Can you suggest me how can i get this issue fix in urgent bases.

2021-06-21 13:49 UTC, stuartmorgan commented
Please see my comment above about how reviews are prioritized.

Also, to save time once it reaches the review stage: the first thing a reviewer would currently say is that this PR [can't process without tests](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#welcome). Implementing tests now will save significant time once the review starts.

2021-06-21 13:52 UTC, vanlooverenkoen commented
I am not an iOS dev. So I have no idea how I should start with the integration tests. If someone could help me with that. That would be nice. Otherwise this PR that we are using in production for 6 months now will never be merged I guess.

2021-07-24 15:22 UTC, vanlooverenkoen commented
@stuartmorgan. Is there somebody who can help me with these tests?

2021-07-24 16:48 UTC, stuartmorgan commented
> @stuartmorgan. Is there somebody who can help me with these tests?

When it reaches review whoever is reviewing it can help with writing tests, yes. (Also, anyone interested in this PR should feel free to help with tests.)

This will likely need XCTests, which unfortunately I can't point to similar examples for in this plugin as there's a lot of missing test coverage right now.

2021-07-24 16:52 UTC, vanlooverenkoen commented
Yes indeed. If anyone wants to help with this please let me know. 

This needs to be merged because it is a missing feature on iOS that works perfectly on android. We are using this in production for over 5 months now.

2021-07-24 21:14 UTC, stuartmorgan commented
> This needs to be merged

Nobody has suggested that it won't be merged, but it also needs to follow our process and requirements.

> We are using this in production for over 5 months now.

And tests will ensure that everyone will be able to use it in their production apps, without it regressing later. The difference between your branch and the actual repository is that you are presumably not accepting lots patches from a variety of people making their own changes to the plugin, any of which could potentially break existing functionality.

2021-07-24 21:18 UTC, vanlooverenkoen commented
Yes of course. But it is quite hard to find the right people to get me started with the tests :D Thanks anyway for your review already.

2021-09-11 19:33 UTC, junwha0511 commented
Is there nobody who can write the XCTest for him?
Many people are waiting for this branch to merge.

2021-10-30 08:17 UTC, vanlooverenkoen commented
Anybody?

2022-01-18 16:43 UTC, stuartmorgan requested changes
Can you elaborate on what help specifically you are looking for on the testing aspect?Unit testing seems like it should be relatively straightforward, but I haven't looked in detail so maybe I'm missing something:
- Tests for the new `FLTPolylinePattern`
- Tests that calling `setPattern` populates `_polyline.spans` correctly

2022-01-18 16:43 UTC, stuartmorgan commented on packages/google_maps_flutter/google_maps_flutter/ios/Classes/JsonConversions.h
> +@interface FLTPolylinePattern : NSObject
This class and its properties and methods need comments, per the style guide. (The existing code in this class unfortunately doesn't follow style, but that shouldn't be perpetuated to new code.)

2022-01-18 16:43 UTC, stuartmorgan commented on packages/google_maps_flutter/google_maps_flutter/ios/Classes/GoogleMapPolylineController.m
> +  NSMutableArray* lengths = [[NSMutableArray alloc] init];
These can be pre-created with size equal to `_pattern`'s size to avoid unnecessary reallocations.

2022-01-18 16:45 UTC, vanlooverenkoen commented
> Can you elaborate on what help specifically you are looking for on the testing aspect? Unit testing seems like it should be relatively straightforward, but I haven't looked in detail so maybe I'm missing something:
> 
> * Tests for the new `FLTPolylinePattern`
> * Tests that calling `setPattern` populates `_polyline.spans` correctly

I have no Swift or Objective C experience. I looked at the native Android code and tried to figure out, by trial and error to get the implementation correct.

2022-01-18 17:11 UTC, stuartmorgan commented
Have you looked at tests for other plugins? https://github.com/flutter/plugins/blob/main/packages/webview_flutter/webview_flutter_wkwebview/example/ios/RunnerTests/FLTCookieManagerTests.m for instance demonstrates some relatively straightforward unit tests.

2022-02-08 06:19 UTC, zzimickQ commented
Hey, guys this PR has been open for 14 months. can someone please just fix the comments and merge it?

2022-02-08 10:55 UTC, stuartmorgan commented
@zzimickQ You are welcome to contribute the necessary tests.

2022-02-08 16:21 UTC, closed without merging