[url_launcher] Fixes for Dart plugin registry
flutter/plugins pull request #3464
Opened 2021-01-26 02:16 UTC by blasten

Required for https://github.com/flutter/flutter/issues/52267

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2021-01-26 03:00 UTC, stuartmorgan requested changes
Many of the changes here don't really make sense; path_provider_{windows,linux} and shared_preferences_{windows,linux} are the plugins that need the registry.

2021-01-26 03:00 UTC, stuartmorgan commented on packages/url_launcher/url_launcher/CHANGELOG.md
> +* Fixes for Dart plugin registry.
While we should fix the typos, url_launcher's desktop implementations don't need a Dart registry, so this description doesn't really make sense.

2021-01-26 03:00 UTC, stuartmorgan commented on packages/url_launcher/url_launcher_linux/lib/url_launcher_linux.dart
> +    // todo
There's nothing to do here; I don't see any purpose this method could ever serve (per the comment above).

2021-01-26 03:00 UTC, stuartmorgan commented on packages/url_launcher/url_launcher_linux/pubspec.yaml
> +    implements: url_launcher
Did this ever end up being used anywhere? I remember that it was in the spec, so we should do it, but is something reading it?

2021-01-26 03:00 UTC, stuartmorgan commented on packages/url_launcher/url_launcher_linux/pubspec.yaml
> +        dartPluginClass: UrlLauncherLinux
Remove, per comment in the other file.

2021-01-26 03:00 UTC, stuartmorgan commented on packages/url_launcher/url_launcher_macos/CHANGELOG.md
> +* Fixes for Dart plugin registry.
Same comments throughout.

2021-01-26 03:00 UTC, stuartmorgan commented on packages/url_launcher/url_launcher_windows/CHANGELOG.md
> +* Fixes for Dart plugin registry.
And here.

2021-01-26 03:31 UTC, Sunbreak commented on packages/url_launcher/url_launcher_windows/pubspec.yaml
>          pluginClass: UrlLauncherPlugin
If `dartPluginClass` takes response, maybe `pluginClass` could be removed?

2021-02-03 23:40 UTC, blasten commented
Closing as this isn't relevant anymore. Will follow up with a smaller fix for the typo in the pubspec.

2021-02-03 23:40 UTC, closed without merging