[image_picker] Migrate image_picker_web to null-safety
flutter/plugins pull request #3535
Opened 2021-02-10 15:57 UTC by Sameerkash

Migrate` image_picker_web to null-safety`

closes flutter/flutter#75162

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2021-02-10 20:03 UTC, ditman requested changes
I think overall this is really good, I cloned the package and tests are passing!

I only made a few comments in a couple of places where I think the null safety is a little bit odd.

The only merge blocker is the version applied to this package. This was promised to be forwards-compatible with 1.0.0 at some point, so we can't use that version. This should be bumped to 2.0.0-nullsafety.

2021-02-12 23:50 UTC, ditman approved these changes
This looks great! Let's merge!

2021-02-12 23:51 UTC, merged

2021-02-13 00:56 UTC, ditman commented
Published, and tagged: https://pub.dev/packages/image_picker_for_web/versions/2.0.0-nullsafety

Thanks again, @Sameerkash !!

2021-02-13 01:23 UTC, Sameerkash commented
> Published, and tagged: https://pub.dev/packages/image_picker_for_web/versions/2.0.0-nullsafety
> 
> Thanks again, @Sameerkash !!

Thanks, @ditman, Learnt a lot and look forward to contributing more if you could suggest more issues.

2021-02-16 18:52 UTC, ditman commented
> if you could suggest more issues.

@Sameerkash check this one out: https://github.com/flutter/flutter/issues/75247

I don't think anybody is looking at: `extension_google_sign_in_as_googleapis_auth` right now, if you want to keep doing null-safety related tasks! :)