[google_maps_flutter] embedded_views_preview not required since v1.0.0
flutter/plugins pull request #3625
Opened 2021-02-24 21:09 UTC by FlorisDevreese

The [release notes](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md#100---out-of-developer-preview--) state that `io.flutter.embedded_views_preview` is not required since version `1.0.0`.

Thus removed this from the example, to keep things clean and tidy ✨

2021-02-24 21:11 UTC, cyanglaz requested changes
The change looks good but please sign the CLA :)

2021-02-24 21:17 UTC, FlorisDevreese commented
@googlebot I signed it!

2021-02-24 21:42 UTC, cyanglaz approved these changes
LGTM

2021-02-25 20:07 UTC, stuartmorgan commented
Landing on red since the two red runs are https://github.com/flutter/flutter/issues/76805

2021-02-25 20:08 UTC, merged