[google_sign_in] Updates google_sign_in_platform_interfaces adding parametrized `clientId`
flutter/plugins pull request #3686
Opened 2021-03-05 18:58 UTC by ggirotto

This PR adds support to https://github.com/flutter/plugins/pull/3640 by parametrizing `clientId` property in `MethodChannelGoogleSignIn`

*List which issues are fixed by this PR. You must list at least one issue.*

Same issues as https://github.com/flutter/plugins/pull/3640

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2021-03-05 18:59 UTC, ggirotto commented
Testes to `google_sign_in` were added at https://github.com/flutter/plugins/pull/3640, which will complement the current PR changes

2021-03-05 19:27 UTC, cyanglaz commented
platform interface change should also be testable through unit tests.

2021-03-05 20:10 UTC, ggirotto commented
@cyanglaz Updated `Other functions pass through arguments to the channel` test which covers parametrized arguments in `init` function

2021-03-05 20:25 UTC, cyanglaz approved these changes
LGTM! Thanks

2021-03-05 20:25 UTC, cyanglaz commented on packages/google_sign_in/google_sign_in_platform_interface/CHANGELOG.md
> +## 2.0.1
```suggestion
## 2.0.1

```

2021-03-05 20:25 UTC, cyanglaz commented on packages/google_sign_in/google_sign_in_platform_interface/pubspec.yaml
> +version: 2.0.1
2.1.0

2021-03-05 20:26 UTC, cyanglaz requested changes
Need to update the minor version because there's a public api change.

2021-03-05 20:42 UTC, ggirotto commented
@cyanglaz done!

2021-03-06 01:35 UTC, cyanglaz commented on packages/google_sign_in/google_sign_in_platform_interface/CHANGELOG.md
> +## 2.1.0
need extra line after version :) 
```suggestion
## 2.1.0

```

2021-03-06 01:38 UTC, cyanglaz reviewed
Actually im sorry. The clientId field was an existing unused filed in the public API, so your initial version was correct
ill change it back

2021-03-06 01:39 UTC, cyanglaz reviewed
Rebasing master should fix ci

2021-03-06 11:14 UTC, ggirotto commented
@cyanglaz Now I think its good. Please let me know if it need more adjustments

2021-03-06 17:39 UTC, cyanglaz approved these changes
LGTM

2021-03-06 17:39 UTC, merged