Added pickMultiImage to image_picker_platform_interface
flutter/plugins pull request #3782
Opened 2021-04-02 09:19 UTC by danielroek

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I signed the [CLA].
- [ ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2021-04-07 07:19 UTC, mvanbeusekom requested changes
Look good to me, just one test missing and 2 small nits on local fields that could be marked `final`.

2021-04-07 07:19 UTC, mvanbeusekom commented on packages/image_picker/image_picker_platform_interface/lib/src/method_channel/method_channel_image_picker.dart
> +    }
It looks like this check is not tested, would be good to also add a quick using test making sure te boundries work.

2021-04-07 07:19 UTC, mvanbeusekom commented on packages/image_picker/image_picker_platform_interface/lib/src/method_channel/method_channel_image_picker.dart
> +    List<dynamic>? paths = await _pickMultiImagePath(
nit: could be marked `final`:

```suggestion
    final List<dynamic>? paths = await _pickMultiImagePath(
```

2021-04-07 07:19 UTC, mvanbeusekom commented on packages/image_picker/image_picker_platform_interface/lib/src/method_channel/method_channel_image_picker.dart
> +    List<PickedFile> files = [];
nit: could be marked `final`:

```suggestion
    final List<PickedFile> files = [];
```

2021-04-07 17:23 UTC, cyanglaz approved these changes
LGTM % nits

2021-04-07 17:23 UTC, cyanglaz commented on packages/image_picker/image_picker_platform_interface/CHANGELOG.md
> +* Added pickMultiImage method
```suggestion
* Add `pickMultiImage` method.
```

2021-04-13 06:56 UTC, mvanbeusekom approved these changes
LGTM! Thanks @danielroek

2021-04-13 06:56 UTC, merged