[camera] android-rework part 1: Base classes to support Android Camera features
flutter/plugins pull request #3795
Opened 2021-04-08 11:49 UTC by mvanbeusekom

Introduces some base classes in the Android Camera implementation which will allow us to separate specific feature logic from the `Camera` class into specific feature classes. This has the following benefits (basically all benefits of the Separation of Concerns principle):

- It allows for focussed feature classes making it easier to maintain the implementation of the feature;
- It will reduce the amount of code currently in the `Camera` class, making it easier to maintain the `Camera` class;
- It will be easier to write unit-tests to cover the feature logic.

This is a first in a series of pull-requests which will gradually introduce changes from PR #3651, making it easier to review the code (as discussed with @stuartmorgan).

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
  - Since this will be a series of pull-requests I will update the version in the last PR of the series.
- [ ] I updated CHANGELOG.md to add a description of the change.
  - Since this will be a series of pull-requests I will update the version in the last PR of the series.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2021-04-08 12:15 UTC, acoutts commented
@googlebot I consent.

2021-04-09 19:10 UTC, stuartmorgan commented
FYI I'm OOO at the moment but will start working through these reviews as time allows.

2021-04-19 19:03 UTC, bparrishMines approved these changes
LGTM

2021-04-19 19:26 UTC, stuartmorgan requested changes
Just small nits, otherwise looks good.

2021-04-19 19:26 UTC, stuartmorgan commented on packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/CameraProperties.java
> +  String getCameraName();
It's not obvious what most of these methods mean. Please add Javadoc comments to each public method (as required by style); it seems like the best option would probably be to document them by indicating what CameraCharacteristics entry each one maps to.

2021-04-19 19:26 UTC, stuartmorgan commented on packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/CameraProperties.java
> +  @RequiresApi(api = VERSION_CODES.P)
Maybe this is a Java noob question, but shouldn't this be on the interface, not the implementation? It's not clear to me what it means for an interface with no API requirement to be implemented by something that does have one.

2021-04-19 19:26 UTC, stuartmorgan commented on packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/features/CameraFeature.java
> +   * Get the current value of this feature's setting.
What is the expected behavior of get/set if `checkIsSupported` returns false? That would be good to document.

2021-04-19 19:26 UTC, stuartmorgan commented on packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/features/CameraFeature.java
> +   * Returns whether or not this feature is supported.
Nit: please use consistent mood in declaration comments (e.g., the above is Sets, not Set, but this is Returns, not Return.)

It looks like the preferred style for Javadoc is declarative, so this is correct and the other methods here should be Gets, Sets, Updates.

2021-04-20 14:05 UTC, stuartmorgan approved these changes
LGTM

2021-04-21 11:18 UTC, merged