[camera] android-rework part 2: Android auto focus feature
flutter/plugins pull request #3796
Opened 2021-04-08 12:39 UTC by mvanbeusekom

Adds the `AutoFocusFeature` containing the implementation to handle auto focus via the Android Camera2 API.

This is a second in a series of pull-requests which will gradually introduce changes from PR #3651, making it easier to review the code (as discussed with @stuartmorgan).

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
  - Since this will be a series of pull-requests I will update the version in the last PR of the series.
- [ ] I updated CHANGELOG.md to add a description of the change.
  - Since this will be a series of pull-requests I will update the version in the last PR of the series.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2021-04-08 14:48 UTC, acoutts commented
@googlebot I consent.

2021-04-20 14:25 UTC, stuartmorgan requested changes
A few small things, but looks good overall. (I only reviewed the new files; I'm assuming there were no changes to the files that are part of "part 1")

2021-04-20 14:25 UTC, stuartmorgan commented on packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/features/autofocus/AutoFocusFeature.java
> +  // the appropriate setting here.
I have no idea who/what the "we"s in this sentence refer to. It doesn't even feel like they are referring to the same thing; setting a private field would be done internally to the class, but recreating the feature would be done from outside the class. Please use clear subjects in the comment instead.

"we" is almost always problematic in (non-TODO) comments, as this ambiguity is extremely common; I advise against using it in comments.

2021-04-20 14:25 UTC, stuartmorgan commented on packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/features/autofocus/AutoFocusFeature.java
> +  public AutoFocusFeature(CameraProperties cameraProperties, boolean recordingVideo) {
Please add Javadoc

2021-04-20 14:25 UTC, stuartmorgan commented on packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/features/autofocus/AutoFocusFeature.java
> +    // final Float maxFocus = cameraCharacteristics.get(CameraCharacteristics.LENS_INFO_HYPERFOCAL_DISTANCE);
Why is there commented out code?

2021-04-20 14:25 UTC, stuartmorgan commented on packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/features/autofocus/AutoFocusFeature.java
> +    }
Consider a ternary so the assignment and declaration are the same statement: `boolean isFixedLength = minFocus == null ? true : (minFocus == 0);`

2021-04-20 14:25 UTC, stuartmorgan commented on packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/features/autofocus/AutoFocusFeature.java
> +        /** If we're locking AF we should do a one-time focus, then set the AF to idle */
s/If we're locking AF we should do/When locking AF do/

Although it's not entirely clear to me what this comment is describing; is the line that is being commented actually setting auto-focus to idle?

2021-04-21 12:02 UTC, mvanbeusekom commented on packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/features/autofocus/AutoFocusFeature.java
> +  public AutoFocusFeature(CameraProperties cameraProperties, boolean recordingVideo) {
done

2021-04-27 15:15 UTC, stuartmorgan approved these changes
LGTM, sorry for the delay.

2021-04-27 15:16 UTC, merged