Improve google_sign_in example
flutter/plugins pull request #3858
Opened 2021-05-06 18:55 UTC by kevmoo

Towards https://github.com/flutter/flutter/issues/78073

2021-05-07 15:04 UTC, stuartmorgan requested changes
@ditman would be a better reviewer for the code change than me.

2021-05-07 17:29 UTC, kevmoo commented on packages/google_sign_in/google_sign_in/example/lib/main.dart
> +import 'package:extension_google_sign_in_as_googleapis_auth/extension_google_sign_in_as_googleapis_auth.dart';
Or we could drastically simplify this example to just show someones email.

Then put the "real" example in the extension package.

Thoughts @ditman ?

2021-05-07 19:55 UTC, ditman commented on packages/google_sign_in/google_sign_in/example/lib/main.dart
> +import 'package:extension_google_sign_in_as_googleapis_auth/extension_google_sign_in_as_googleapis_auth.dart';
I think there was value in the old example by doing a raw request to a google service too.

Do you know of any writeup on how to access a raw google API through flutter that is not covered by googleapis? For example: Google Photos?

2021-05-07 20:14 UTC, kevmoo commented on packages/google_sign_in/google_sign_in/example/lib/main.dart
> +import 'package:extension_google_sign_in_as_googleapis_auth/extension_google_sign_in_as_googleapis_auth.dart';
I don't know of any write-up, although some of the JSON endpoints are documented.

I can revert this and put it in the extension.

2021-05-10 22:24 UTC, kevmoo commented
Closing this out. Will do something else here!

2021-05-10 22:24 UTC, closed without merging