[in_app_purchase] Android example using in_app_purchase_android package
flutter/plugins pull request #3861
Opened 2021-05-07 14:20 UTC by mvanbeusekom

Adds the example app for the in_app_purchase_android platform implementation. 

- Adds the Android implementation for issue flutter/flutter#81695

**NOTE:** this PR builds on top of the "[[in_app_purchase] Federated Android implementation](https://github.com/flutter/plugins/pull/3841)" pull request. If have split in into a separate PR so it would be easier to review.

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`. See [plugin_tool format](../script/tool/README.md#format-code))
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

2021-05-11 21:21 UTC, cyanglaz requested changes

2021-05-11 21:21 UTC, cyanglaz commented on packages/in_app_purchase/in_app_purchase_android/example/pubspec.yaml
> +    path: ../../in_app_purchase_platform_interface
this needs to be replaced

2021-05-11 21:21 UTC, cyanglaz commented on packages/in_app_purchase/in_app_purchase_android/example/pubspec.yaml
> +  shared_preferences: ^2.0.0-nullsafety.1
can this be ^2.0.0?

2021-05-12 05:39 UTC, mvanbeusekom commented on packages/in_app_purchase/in_app_purchase_android/example/pubspec.yaml
> +    path: ../../in_app_purchase_platform_interface
Done

2021-05-12 05:40 UTC, mvanbeusekom commented on packages/in_app_purchase/in_app_purchase_android/example/pubspec.yaml
> +  shared_preferences: ^2.0.0-nullsafety.1
Done

2021-05-12 16:06 UTC, cyanglaz approved these changes
LGTM

2021-05-12 16:06 UTC, merged