Update web testing readme instructions
flutter/plugins pull request #4167
Opened 2021-07-19 19:24 UTC by NishantChandla

Updated web testing instructions in example/README.md for web plugins. Latest web-test instructions point to https://github.com/flutter/flutter/wiki/Plugin-Tests#web-tests.

[#76817](https://github.com/flutter/flutter/issues/76817)

cc @ditman 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [ ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

2021-07-19 19:34 UTC, ditman requested changes
Please, remove the "hardcoded" documentation about  Mocks in url_launcher_web and google_maps_flutter_web, and point people to the flutter wiki as well. I've left a small example markdown that should work!

And thanks for your contribution!

2021-07-19 19:34 UTC, ditman commented on packages/url_launcher/url_launcher_web/example/README.md
>  ## Mocks
Mocks are also included in the Wiki above. Let's replace the whole  contents of this section by:

```
See [Plugin Tests > Web Tests > Mocks](https://github.com/flutter/flutter/wiki/Plugin-Tests#mocks)
in the Flutter wiki for more information about the `.mocks.dart` files in this package.
```

(This also happens in the `google_maps_flutter_web` package)

2021-07-19 19:46 UTC, ditman approved these changes
Looking great, I'll have this merged ASAP!

2021-07-19 19:47 UTC, NishantChandla commented
> Looking great, I'll have this merged ASAP!

Thank You! @ditman

2021-07-19 21:31 UTC, merged

2021-07-20 00:44 UTC, vishnuaq commented
Shh

2021-07-20 00:45 UTC, vishnuaq reviewed
**bsnxn**