[webview_flutter] Extract Android implementation into a separate package
flutter/plugins pull request #4343
Opened 2021-09-14 10:25 UTC by mvanbeusekom

This PR puts the native Android implementation of the platform interface (which was separated in #4302) into its own package, in preparation for moving the main plugin to a federated architecture.

Relevant issue:
 - flutter/flutter#86286

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

2021-09-14 13:15 UTC, BeMacized commented
@flutter/googlebot I consent.

2021-09-14 13:25 UTC, BeMacized commented
@googlebot I consent.

2021-09-15 20:41 UTC, stuartmorgan requested changes

2021-09-15 20:41 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter_android/pubspec.yaml
> +version: 0.0.1
Same version comment here as for iOS.

2021-09-15 20:41 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter_android/example/lib/main.dart
> +/// A web view widget for showing html content.
Same comment here as for iOS about moving to a separate file.

2021-09-15 20:41 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter_android/example/integration_test/webview_flutter_test.dart
> +  const bool _skipDueIssue86757 = true;
Nit: _skipDueToIssue86757

2021-09-20 20:03 UTC, stuartmorgan approved these changes
Changes LGTM

2021-09-21 06:40 UTC, merged