[google_maps_flutter] Clear duplicated dependencies
flutter/plugins pull request #4484
Opened 2021-11-08 08:40 UTC by kodal

Remove duplicated dependencies according by [dart-lang/pub#2101]

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[dart-lang/pub#2101]: https://github.com/dart-lang/pub/issues/2101

2021-11-11 21:18 UTC, stuartmorgan requested changes
Thanks for the submission!

This needs a `CHANGELOG.md` update using `## NEXT` as the version, but otherwise looks good.

2021-11-12 04:54 UTC, kodal commented
Thanks for review!

Added description to `CHANGELOG.md`.

2021-11-12 14:09 UTC, stuartmorgan requested changes

2021-11-12 14:09 UTC, stuartmorgan commented on packages/google_maps_flutter/google_maps_flutter/CHANGELOG.md
> +## 2.1.1
This should not be a version bump as it does not affect customers of the package. It should use `NEXT`, per my earlier comment.

2021-11-12 15:14 UTC, stuartmorgan approved these changes
LGTM, thanks!

2021-11-12 15:14 UTC, stuartmorgan commented
@cyanglaz Could you do the secondary review here?

2021-12-09 15:49 UTC, stuartmorgan commented
Tagging @bparrishMines for secondary review of this trivial cleanup.

2021-12-14 15:51 UTC, stuartmorgan commented
@cyanglaz @bparrishMines Ping for one of you to sign off on this per two-review policy?

2021-12-14 15:53 UTC, stuartmorgan commented
@kodal Some of the tests never started for some reason; could you merge in the latest `master` to kick off a new round of tests?

2021-12-14 16:52 UTC, cyanglaz approved these changes
LGTM

2021-12-16 17:47 UTC, bparrishMines approved these changes
LGTM

2022-01-04 16:14 UTC, stuartmorgan commented
@kodal Are you planning on merging in master so we can land this? I'm not able to do so from the GitHub UI any more for some reason.

2022-01-20 16:21 UTC, merged