[url_launcher] Add null check for extracting browser headers
flutter/plugins pull request #4507
Opened 2021-11-12 22:51 UTC by camsim99

Adds null check for extracting browser headers.

Addresses [Issue #72863](https://github.com/flutter/flutter/issues/72863#issuecomment-966652453).

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [ ] I signed the [CLA].
- [ ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

2021-11-12 23:29 UTC, blasten commented on packages/url_launcher/url_launcher/CHANGELOG.md
> +* Fixed extracting browser headers when they are null error.
```suggestion
## NEXT

* Fixed extracting browser headers when they are null error.
```

2021-11-12 23:31 UTC, blasten commented on packages/url_launcher/url_launcher/android/src/test/java/io/flutter/plugins/urllauncher/WebViewActivityTest.java
> +    assertEquals(WebViewActivity.extractHeaders(headersBundle), expectedExtractedHeaders);
```suggestion
    assertEquals(WebViewActivity.extractHeaders(null), Collections.emptyMap());
```

2021-11-12 23:31 UTC, blasten approved these changes
LGTM % nits

2021-11-12 23:31 UTC, blasten commented on packages/url_launcher/url_launcher/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java
> +  public static Map<String, String> extractHeaders(@Nullable Bundle headersBundle) {
nit: missing annotation: `@visibleForTesting`

2021-11-13 00:53 UTC, stuartmorgan requested changes

2021-11-13 00:53 UTC, stuartmorgan commented on packages/url_launcher/url_launcher/CHANGELOG.md
> +## NEXT
We should do a version bump on this; we only use `NEXT` when we don't want to publish changes (e.g., test-only changes)

2021-11-14 15:17 UTC, stuartmorgan approved these changes
`pubspec.yaml` needs to be updated with the new version (which is why the `publishable` step is failing); otherwise, LGTM. Thank for taking care of this!

2021-11-15 21:21 UTC, merged