[path_provider] Add `getFlutterAssetsPath()` interface method.
flutter/plugins pull request #4516
Opened 2021-11-17 08:53 UTC by mvanbeusekom

Adds the `getFlutterAssetsPath()` method to the path_provider_platform_interface. Platform implementations of the `getFlutterAssetsPath()` method should return the path to the directory which is used by the Flutter framework to store
the assets registered in the pubspec.yaml file of a Flutter application.

Related to issue flutter/flutter#34026

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2021-11-17 09:39 UTC, BeMacized requested changes
Two inconsistencies, also still requires a format.

2021-11-17 09:39 UTC, BeMacized commented on packages/path_provider/path_provider_platform_interface/test/method_channel_path_provider_test.dart
> +          case 'getFlutterAssetPath':
```suggestion
          case 'getFlutterAssetsPath':
```

2021-11-17 09:39 UTC, BeMacized commented on packages/path_provider/path_provider_platform_interface/CHANGELOG.md
> +* Added `getFlutterAssetPath` interface method which when implemented should return the path where Flutter stored the assets registered in the pubspec.yaml file.
```suggestion
* Added `getFlutterAssetsPath` interface method which when implemented should return the path where Flutter stored the assets registered in the pubspec.yaml file.
```

2021-11-17 10:16 UTC, mvanbeusekom commented on packages/path_provider/path_provider_platform_interface/CHANGELOG.md
> +* Added `getFlutterAssetPath` interface method which when implemented should return the path where Flutter stored the assets registered in the pubspec.yaml file.
Fixed.

2021-11-17 10:33 UTC, BeMacized approved these changes
LGTM

2021-11-17 16:35 UTC, stuartmorgan commented
I don't think we want to provide this as a directory; the plugin APIs on iOS and Android that we would use to implement this take an asset key (the relative "path" in the pubspec.yaml, I belive), and optional package name (I'm not sure if we need to expose that or not?), and return a path. There's nothing in the structure there that guarantees a common root directory.

And actually, looking at the Android version, it mentions that what it returns is for use with `AssetManager`. @blasten Does that mean that we can't return that as a path for people to do `File` operations on in Dart? If so, that's going to make things tricky.

2022-01-14 07:54 UTC, mvanbeusekom commented
Closing this PR since this feature isn't feasible on Android.

2022-01-14 07:54 UTC, closed without merging