[webview_flutter] Add setCookie to CookieManager and support initial cookies in creation params.
flutter/plugins pull request #4561
Opened 2021-12-01 08:44 UTC by BeMacized

This PR adds a function for setting cookies to the CookieManager, as well support for setting initial cookies through the `CreationParams` object.

As this PR depends on, and contains the changes of, updates made to the platform interface in #4555, as well as the platform specific implementations in #4556 and #4557, this PR will remain in draft mode until those changes have been merged and published.

Relevant issue:
- flutter/flutter#27597

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2021-12-07 17:46 UTC, stuartmorgan reviewed
Drive-by comment nit.

2021-12-07 17:46 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter/lib/src/webview.dart
> +  /// This is a no op on iOS versions below 9.
We don't support versions below 9 any more, so you can just remove this.

2021-12-07 20:02 UTC, stuartmorgan commented
Dependencies are published; this is ready to be finalized.

2021-12-07 20:14 UTC, stuartmorgan requested changes
Just minor things; looks good overall.

2021-12-07 20:14 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter/CHANGELOG.md
> +* Added `setCookie` to CookieManager.
Nit: Adds

2021-12-07 20:14 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter/pubspec.yaml
> +    path: ../webview_flutter_wkwebview
This didn't get resolved; should be 2.6.0

2021-12-07 20:28 UTC, stuartmorgan approved these changes
LGTM

2021-12-07 20:51 UTC, stuartmorgan commented
`submit-queue` is incorrectly reporting red; overriding.

2021-12-07 20:53 UTC, merged

2022-08-12 10:11 UTC, ismanong commented
Cookies are encoded by default using UrlEncode, which is inconsistent with browser behavior and can cause some possible business problems.

2022-08-12 11:55 UTC, stuartmorgan commented
This PR was landed last year; it can't be changed. If you have an issue to report, please use the issue tracker.