[video_player] BehindLiveWindowException
flutter/plugins pull request #5091
Opened 2022-03-21 13:27 UTC by Ezaldeen99

*Behind window exceptions that happens in live streaming are really annoying and it maybe a bad UX that the user will get an error each time it happens.*

*List which issues are fixed by this PR.*
#100478

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

2022-03-21 18:07 UTC, stuartmorgan commented on packages/video_player/video_player_android/CHANGELOG.md
> +* Handle `BehindLiveWindowException`
Please fix this to follow the CHANGELOG style guide that was linked in the PR checklist. You've checked the box, but aren't actually following the style described there.

2022-03-21 18:10 UTC, stuartmorgan commented
I've updated the checklist to match the actual state of the PR; please re-check the boxes once you've done those steps.

2022-03-21 18:13 UTC, Ezaldeen99 commented
Thanks for your review, will do the requested changes

2022-03-22 11:50 UTC, stuartmorgan requested changes

2022-03-22 11:50 UTC, stuartmorgan commented on packages/video_player/video_player_android/lib/src/android_video_player.dart
> +        case 'behindLiveWindow':
Why is this new event necessary? Is ExoPlayer really starting buffering without calling the listener we have registered?

2022-03-22 11:50 UTC, stuartmorgan commented on packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
> +            if (isBehindLiveWindow(error) && exoPlayer != null) {
All of the changes in this file--which is the core of the PR--could be reverted without any tests failing, so the PR doesn't have meaningful test coverage. This needs a native unit test.

2022-04-12 18:48 UTC, stuartmorgan commented
@Ezaldeen99 Are you still planning to update this PR to address the latest review comments?

2022-04-13 06:53 UTC, Ezaldeen99 commented
> @Ezaldeen99 Are you still planning to update this PR to address the latest review comments?

sorry for latency, I will try to update this PR by the end of the week, thanks for understanding

2022-05-05 20:45 UTC, stuartmorgan commented
Thank you for your contribution. I'm going to close this PR for now since there are outstanding comments, just to get this off our PR review queue. Please don't hesitate to submit a new PR if you have the time to address the review comments. Thanks!

2022-05-05 20:45 UTC, closed without merging