Get available biometrics
flutter/plugins pull request #5127
Opened 2022-03-30 08:27 UTC by RafaRuiz

**[Continuing PR #4874 from @darwin-morocho]**

On Android `canCheckBiometrics` returns true if the device doesn't have any biometric enrolled (For more info check https://github.com/flutter/flutter/issues/45497#issuecomment-1007310214). Now with this PR `canCheckBiometrics` returns false on Android if device has the biometric hardware but doesn't have any biometric enrolled.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [X] I signed the [CLA].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [X] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

2022-04-07 12:37 UTC, RafaRuiz commented
@stuartmorgan  any thoughts?

2022-04-07 14:10 UTC, stuartmorgan requested changes

2022-04-07 14:10 UTC, stuartmorgan commented on packages/local_auth/local_auth/CHANGELOG.md
> +enrolled. For more information check [this](https://github.com/flutter/flutter/issues/45497#issuecomment-1007310214).
The last sentence can be removed; that comment doesn't really have any information that the CHANGELOG entry doesn't.

2022-04-07 14:10 UTC, stuartmorgan commented on packages/local_auth/local_auth/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java
> +      return biometrics;
You haven't addressed my feedback from the previous PR, so this has the same bug as earlier versions of that PR. Please read my comments there regarding the desired behavior with respect to empty lists vs `["undefined"]`.

2022-04-07 14:10 UTC, stuartmorgan commented on packages/local_auth/local_auth/android/src/test/java/io/flutter/plugins/localauth/LocalAuthTest.java
> +  private LocalAuthPlugin plugin = new LocalAuthPlugin();
The object under test should not be part of the test fixture; that's an anti-pattern in unit testing.

2022-04-19 16:28 UTC, RafaRuiz commented on packages/local_auth/local_auth/android/src/test/java/io/flutter/plugins/localauth/LocalAuthTest.java
> +  public void getAvailableBiometrics_withHardwareButNothingEnrolled_ShouldReturnEmpty() {
What I read here is:
- Given that I have hardware available for biometrics.
- When I haven't enrolled to any.
- Then result of the available biometrics is empty.

What am I missing here?

2022-04-19 16:59 UTC, stuartmorgan commented on packages/local_auth/local_auth/android/src/test/java/io/flutter/plugins/localauth/LocalAuthTest.java
> +  public void getAvailableBiometrics_withHardwareButNothingEnrolled_ShouldReturnEmpty() {
See https://github.com/flutter/plugins/pull/4874#discussion_r814094211.

Alternately, now that this package has been federated and switched to an in-package platform channel you could rework the interface such that this was correct without regression other plugins, but this PR currently isn't doing that either.

2022-04-19 18:59 UTC, RafaRuiz commented
In my latest commit, I'm reverting so only the `local_auth_android` is changed to version 1.0.1,
then another PR will proceed after that by changing `local_auth` when `local_auth_android` is published to 1.0.1

2022-04-19 19:00 UTC, RafaRuiz commented on packages/local_auth/local_auth/android/src/test/java/io/flutter/plugins/localauth/LocalAuthTest.java
> +  public void getAvailableBiometrics_withHardwareButNothingEnrolled_ShouldReturnEmpty() {
Ok, please check the latest version :)
I apologise if this is not very clear as I'm adopting a PR from 1.x to 2.x and it's a bit of a mess :D

2022-04-20 19:10 UTC, stuartmorgan reviewed
It seems like there's still a fundamental miscommunication about how this interacts with the Dart side of the plugin.

Given that https://github.com/flutter/plugins/pull/5309 was just opened with correct behavior and test structure, I'm going to close in favor of that PR, but thanks for the submission!

2022-04-20 19:10 UTC, stuartmorgan commented on packages/local_auth/local_auth_android/android/src/main/java/io/flutter/plugins/localauth/LocalAuthPlugin.java
> +      biometrics.add("undefined");
This is the opposite of what the Dart code is expecting, so this doesn't fix my comment, and also breaks the reverse case.

2022-04-20 19:10 UTC, closed without merging