fix: 'messages.g.h' file not found
flutter/plugins pull request #5635
Opened 2022-05-05 06:54 UTC by hueyzng

<img width="996" alt="Screen Shot 2022-05-05 at 14 53 32" src="https://user-images.githubusercontent.com/14038071/166875190-da0c91aa-4184-4822-b937-339918bf1d07.png">

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2022-05-05 19:47 UTC, stuartmorgan commented
Thanks for the contribution! You’ve checked boxes in the PR checklist above that are not reflected in this PR, so I’m assuming this is a work in progress and am marking it as a Draft. Please review the checklist, updating the PR as appropriate, and when the checklist reflects the state of the PR as posted please feel free to mark it as ready for review.

In particular, you haven't done either of these steps, which are required:

> * [x]  I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning), or this PR is [exempt from version changes](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates).
> * [x]  I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style).

2022-05-06 14:37 UTC, stuartmorgan requested changes

2022-05-06 14:37 UTC, stuartmorgan commented on packages/image_picker/image_picker/CHANGELOG.md
> +## 0.8.6
Please revert the changes to `image_picker`; there's no need to update the app-facing dependencies for a bugfix in an implementation package.

2022-05-06 14:37 UTC, stuartmorgan commented on packages/image_picker/image_picker_ios/CHANGELOG.md
> +## 0.8.6
Please see https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#updating-a-changelog-that-has-a-next

2022-05-06 14:37 UTC, stuartmorgan commented on packages/image_picker/image_picker_ios/pubspec.yaml
> +version: 0.8.6
This is a bugfix of a pre-1.0 package, so should update the build number instead. So this should be 0.8.5+1.

2022-05-06 14:38 UTC, stuartmorgan commented
@hueyzng By the way, is there anything unusual about your setup (e.g., are you using add-to-app or something along those lines)? The change is clearly correct, but I'm wondering why our CI wasn't affected by the issue.

2022-05-07 00:58 UTC, hueyzng commented
@stuartmorgan I don't have any special settings. I just run flutter pub add image_picker and then run the ios project and it reports this error.

2022-05-07 01:11 UTC, hueyzng commented
Please review my changes again is there anything else wrong with them. I'd be happy to fix it.

2022-05-07 01:25 UTC, stuartmorgan commented
> I don't see CI running build tests on a mac

I'm not sure where you are looking exactly, but every plugin is built for every supported platform (multiple times, in fact) on every CI run.

2022-05-07 03:30 UTC, hueyzng commented
Sorry it's my fault. I only just saw the .ci/scripts/build_all_plugins.sh file. Now I see the macOS tasks at .cirrus.yml. When I try to build packages/image_picker/image_picker_ios/example locally, it does build successfully using both angled and quotes include. I don't understand how using angled include can be built successfully, but on my project that is failed.

![image](https://user-images.githubusercontent.com/14038071/167236304-b7288ee0-88c3-4350-8b48-04e3164b07c4.png)

2022-05-09 19:05 UTC, stuartmorgan commented
> I don't understand how using angled include can be built successfully, but failed in my project.

It may depend on project-level search path settings.

2022-05-09 19:06 UTC, stuartmorgan requested changes

2022-05-09 19:06 UTC, stuartmorgan commented on packages/image_picker/image_picker/pubspec.yaml
> +  image_picker_ios: ^0.8.5+1
Please revert this change, per my previous comment.

2022-05-09 19:06 UTC, stuartmorgan commented on packages/image_picker/image_picker_ios/CHANGELOG.md
> +* Fix 'messages.g.h' file not found.
Fixes

2022-05-09 19:12 UTC, Hixie commented
i presume that testing this is intractable because of the number of potential configurations we would have to test to catch this kind of thing?

test-exempt: intractable, assuming i'm right that it would not be practical to actually test for this

2022-05-09 19:28 UTC, stuartmorgan commented
> i presume that testing this is intractable because of the number of potential configurations we would have to test to catch this kind of thing?

I checked the example, and I don't see anything that would be causing us to find local headers when using system include style (`<>`). If we figure out what causes it we could change it in our example apps, but it looks like it's more subtle than just "remove some Xcode-default-template set of search paths".

@hueyzng If you see what's different in your project's build settings and the example's build settings that causes this, please let us know.

2022-05-10 02:16 UTC, stuartmorgan requested changes

2022-05-10 02:16 UTC, stuartmorgan commented on packages/image_picker/image_picker_ios/CHANGELOG.md
> +* Fixes 'messages.g.h' file not found.
You've merged incorrectly here; you're now adding to the change list for a version that has already been published. You need a new version bump.

2022-05-11 08:29 UTC, keviner2004 commented
I have the error when I use `flutter run` to run `module` project with dependency `image_picker ^0.8.5+1` on iOS simulator.

`Lexical or Preprocessor Issue (Xcode): 'messages.g.h' file not found with <angled> include; use "quotes" instead`

2022-05-11 18:38 UTC, stuartmorgan approved these changes
LGTM

2022-05-15 09:40 UTC, stuartmorgan commented
@cyanglaz Ping on final review here.

2022-05-16 17:20 UTC, cyanglaz approved these changes
LGTM! Thanks!

2022-05-16 17:24 UTC, merged

2022-05-20 11:06 UTC, mukkoticf commented
Please update this fix in **image_picker** package also. I can see **image_picker_ios** version is old in pubspec.yaml of **image_picker**

2022-05-20 11:26 UTC, stuartmorgan commented
> Please update this fix in **image_picker** package also.

This issue doesn't exist in that package, so there's nothing to fix.

> I can see **image_picker_ios** version is old in pubspec.yaml of **image_picker**

No, you can see that the *minimum* version is older than this. Which is an accurate expression of what that package actually requires.

You just need to `dart pub upgrade`.

2022-05-23 08:46 UTC, mukkoticf commented
Thank you @stuartmorgan . This worked