ignore upcoming warnings in  webview_flutter_wkwebview.
flutter/plugins pull request #5856
Opened 2022-05-30 06:55 UTC by a14n

Following up on #5852 for changes in webview_flutter_wkwebview.

This PR will prevent warnings once https://github.com/flutter/flutter/pull/104231 has landed.

2022-05-31 14:24 UTC, stuartmorgan requested changes

2022-05-31 14:24 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter_wkwebview/CHANGELOG.md
> +* Fixes unnecessary imports after [adding some exports of public API in foundation/serialization.dart](https://github.com/flutter/flutter/pull/104231).
Same comment here: https://github.com/flutter/plugins/pull/5855#discussion_r885707440

2022-05-31 20:09 UTC, a14n commented
PTAL

2022-06-03 08:43 UTC, guidezpl approved these changes

2022-06-03 12:44 UTC, stuartmorgan approved these changes
Same optional version note here.

2022-06-03 12:46 UTC, merged