[github_actions] Add automatic updating of github-actions
flutter/plugins pull request #5919
Opened 2022-06-06 20:31 UTC by drewroengoogle

Reopening the automatic updating of github actions hashes

2022-06-06 20:42 UTC, stuartmorgan requested changes
There's no fix for https://github.com/flutter/plugins/pull/5880#issuecomment-1147652665 here, so this would just break the tree the same way it did last time.

2022-06-06 21:42 UTC, drewroengoogle commented
Thanks for pointing that out. I misunderstood earlier and thought the "red tree" was referencing the android tests that failed last time (https://github.com/flutter/plugins/pull/5880/checks?check_run_id=6697297832)

I've shortened the prefix and the dependabot config was validated successfully. Apologies for the confusion!

2022-06-06 22:15 UTC, stuartmorgan commented
> I misunderstood earlier and thought the "red tree" was referencing the android tests that failed last time

The comment about the red tree was actually about the fact that the current (post-submit test) state of the repository--unrelated to your PR--was red when you submitted, which isn't okay to land non-repairing PRs into. But that was a follow-up to the earlier comment about reverting to fix the new breakage your PR caused.

> (https://github.com/flutter/plugins/pull/5880/checks?check_run_id=6697297832)

This is actually a slightly different issue: these are presubmit tests for your own PR which didn't pass. You should also not land with red presubmit tests. (This is related to the above because one of the presubmit tests is a live state of the tree, so you can't land into a broken tree without also ignoring a failing presubmit check).

2022-06-06 22:17 UTC, stuartmorgan approved these changes

2022-06-07 12:22 UTC, drewroengoogle commented
Got it. Thanks again for your patience on this! Rerunning the failed web-platform_tests step to ensure it's green

2022-06-07 14:16 UTC, merged