Android render
flutter/plugins pull request #6063
Opened 2022-06-30 22:49 UTC by bparrishMines

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [ ] I signed the [CLA].
- [ ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2022-06-30 22:53 UTC, bparrishMines commented on packages/webview_flutter/webview_flutter_android/lib/webview_surface_android.dart
> -/// information.
This is no longer true for this `AndroidView`. I moved it to the new one.

2022-06-30 22:56 UTC, bparrishMines commented on packages/webview_flutter/webview_flutter_android/lib/webview_surface_android.dart
> -              layoutDirection: TextDirection.rtl,
This shouldn't be a breaking change for large majority of people. This value is ignored unless support for this is explicitly added to the `AndroidManifest.xml`. For example, it is still `ltr` in our example app.

2022-06-30 23:01 UTC, bparrishMines commented on packages/webview_flutter/webview_flutter_android/pubspec.yaml
> +  flutter: ">=3.0.0"
Required for `initExpensiveAndroidView`

2022-07-01 18:03 UTC, stuartmorgan requested changes

2022-07-06 22:10 UTC, bparrishMines commented
@stuartmorgan This is ready for another review.

I switched the implementation to use the expensive android view when the background color is set as transparent. Since background color is a creation param, changes to it are ignored after the webview is already built.

2022-07-08 17:36 UTC, stuartmorgan reviewed
Looks like this is breaking tests on the API 26 device? But otherwise LG.

(Based on the findings I wrote up in https://github.com/flutter/flutter/issues/107313 we have other problems with webview that I hadn't realized before, but this change will still be an incremental improvement.)

2022-07-12 21:11 UTC, bparrishMines commented
@stuartmorgan I reran the test and it passed. I believe it was just a timeout. If you believe this is good, could you approve the PR?

2022-07-20 16:26 UTC, merged