[google_sign_in] Add forceCodeForRefreshToken parameter platform implementations
flutter/plugins pull request #6130
Opened 2022-07-21 21:31 UTC by fbcouch

This is the platform implementation companion to https://github.com/flutter/plugins/pull/3356.

## Related Issues

* flutter/flutter#17813
* flutter/flutter#14245
* flutter/flutter#15796
* flutter/flutter#45847

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2022-07-26 13:48 UTC, stuartmorgan commented
It looks like several of the new unit tests are failing; see https://cirrus-ci.com/task/5986776966758400 for details.

2022-07-26 21:36 UTC, fbcouch commented
@stuartmorgan My bad – for whatever reason, Android Studio was loading the tests from the pub version of the plugin instead of the local branch...those are fixed now, and should be using the same style as the other init tests that were added.

2022-08-04 18:12 UTC, stuartmorgan requested changes

2022-08-04 18:12 UTC, stuartmorgan commented on packages/google_sign_in/google_sign_in_android/CHANGELOG.md
> +## 6.0.2
Nit: since you are adding a feature these should be minor version bumps rather than bugfix version bumps.

2022-08-04 18:12 UTC, stuartmorgan commented on packages/google_sign_in/google_sign_in_android/test/google_sign_in_android_test.dart
> -        googleSignIn.init(
Here and on iOS, please add a new test instead of changing the old one, so that we have coverage that `init` hasn't regressed (and doesn't later).

2022-08-17 21:18 UTC, jmagman approved these changes
iOS part LGTM

2022-08-30 14:59 UTC, stuartmorgan approved these changes
LGTM! I'm assuming that @camsim99 has no other comments since the main PR was approved.

2022-08-30 15:00 UTC, merged