fix typo in `setCookieForInsances` method and update CHANGELOG.md
flutter/plugins pull request #6288
Opened 2022-08-17 23:25 UTC by KosukeSaigusa

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [ ] I signed the [CLA].
- [ ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2022-08-17 23:26 UTC, KosukeSaigusa commented
Thank you for kindly reminding me of this PR @jmagman!

I recreated a PR instead of this one:

https://github.com/flutter/plugins/pull/6102

2022-08-17 23:37 UTC, stuartmorgan commented
> I recreated a PR instead of this one from the latest main branch to avoid confusion

Losing all of the context of previous reviews doesn't reduce confusion; is there a technical issue with just updating the existing PR?

2022-08-24 20:18 UTC, jmagman commented
What's the status of this? https://github.com/flutter/plugins/pull/6102 merged, but it was empty?

2022-08-24 20:33 UTC, stuartmorgan commented
> #6102 merged, but it was empty?

I still can't figure out what happened to that PR; the commit hash it lists isn't for that PR. And it says @KosukeSaigusa did the merging into `main`, which isn't possible.

2022-08-24 20:34 UTC, stuartmorgan commented
Regardless, at this point we should just re-review in this new PR.

2022-08-24 20:35 UTC, stuartmorgan requested changes

2022-08-24 20:35 UTC, stuartmorgan commented on packages/webview_flutter/webview_flutter/CHANGELOG.md
> +* Fixes typo in a method name, from `setCookieForInsances` to `setCookieForInstances`.
This needs to be a version change, not a `NEXT`, per repo policy.

2022-09-10 00:19 UTC, bparrishMines commented
@KosukeSaigusa Since this is still waiting on updates, I went ahead and created https://github.com/flutter/plugins/pull/6384 with the updated version bump. Closing in favor of https://github.com/flutter/plugins/pull/6384

2022-09-10 00:19 UTC, closed without merging