[video_player] Update Usage section of README
flutter/plugins pull request #6389
Opened 2022-09-11 20:52 UTC by gabrielbrosula

This PR provides additional context to some of the capabilities of the video_player plugin. Specifically, it adds information on the limitations on the Data Sources and Constructors for the VideoPlayerController, providing information about looping and its interaction with the seekTo method, and closed captioning.

Fixes https://github.com/flutter/flutter/issues/69064.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [X] I signed the [CLA].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [X] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2022-10-21 19:40 UTC, stuartmorgan requested changes
Thanks, this looks like great content to add! I've left some specific comments inline; sorry for the delay in reviewing this.

2022-10-21 19:40 UTC, stuartmorgan commented on packages/video_player/video_player/CHANGELOG.md
> +- Updates README via code excerpts.
It looks like your editor mass-rewrote this file; please revert all of these changes and use `*` for the new section as well.

2022-10-21 19:40 UTC, stuartmorgan commented on packages/video_player/video_player/CHANGELOG.md
> +- Updates README "Usage" section
Nit: This needs a period, per style guide.

2022-10-21 19:40 UTC, stuartmorgan commented on packages/video_player/video_player/README.md
> +| ----------- | ------- | ---- | ----- |
What is the purpose of this change?

2022-10-21 19:40 UTC, stuartmorgan commented on packages/video_player/video_player/README.md
> +Functionality to decode YouTube URIs is not provided by this plugin.
This paragraph seems like an odd thing to single out; `VideoPlayerController.network` takes the URL of a video file, not a web page. There's nothing special about YouTube here.

2022-10-21 19:40 UTC, stuartmorgan commented on packages/video_player/video_player/README.md
> +To learn more about the limitations of `VideoPlayerController` constructors, see the [`Constructors` documentation](https://pub.dev/documentation/video_player/latest/video_player/VideoPlayerControlle
What limitations is this referring to? I don't see any particularly interesting notes in that documentation that some would need to go read in this context.

2022-10-21 19:40 UTC, stuartmorgan commented on packages/video_player/video_player/README.md
> +You can also set the `_controller` to start the video at a specific timestamp by calling `_controller.seekTo`.
How is this related to looping?

2022-10-21 19:40 UTC, stuartmorgan commented on packages/video_player/video_player/README.md
> +Setting looping to true and providing a to the `seekTo` method will start the video again from the provided `moment`.
There's a word or phrase missing here, so I'm not sure what exactly this is trying to say, but as above I'm not sure what the relationship between seeking and looping is here.

2022-10-21 19:40 UTC, stuartmorgan commented on packages/video_player/video_player/README.md
> +For more information on these methods, please refer to the [`setLooping` method documentation]() and the [`seekTo` method documentation]().
These links are missing.

2022-10-21 19:40 UTC, stuartmorgan commented on packages/video_player/video_player/README.md
> +#### Caption Files
These sections are very short, and closely related; I don't think we need sub-headings for each part.

2022-10-21 19:40 UTC, stuartmorgan commented on packages/video_player/video_player/README.md
> +You can access the caption string from the `_controller` using `_controller.value.caption.text`.
(Especially since you've put this in "displaying captions", but it's not actually specific to display.)

2022-10-21 19:40 UTC, stuartmorgan commented on packages/video_player/video_player/README.md
> +
Please remove this, it breaks our snippet management system.

2022-10-21 19:47 UTC, stuartmorgan commented
(I've removed the issue link from the PR description, since this doesn't actually address the issue it referenced. But this PR doesn't need an issue.)

2022-11-17 21:16 UTC, stuartmorgan commented
Are you still planning on updating this PR to address the review comments above?

2022-11-17 21:26 UTC, gabrielbrosula commented
I am currently not planning to update the PR, but I greatly appreciate your
time in reviewing it.

They have informed me greatly about improving my own open-source
contributions in the future.



On Thu, Nov 17, 2022 at 4:17 PM stuartmorgan ***@***.***>
wrote:

> Are you still planning on updating this PR to address the review comments
> above?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/flutter/plugins/pull/6389#issuecomment-1319216543>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATRXFLMN2FQ5TM4GD6FPAC3WI2OEXANCNFSM6AAAAAAQJ5ZYNU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-17 21:31 UTC, stuartmorgan commented
Given that, closing. Please feel free to open a new PR if you decide to revisit this.

2022-11-17 21:31 UTC, closed without merging