[image_picker] Allow saving photos picked with PHPicker without permissions
flutter/plugins pull request #6429
Opened 2022-09-15 06:36 UTC by PiotrMitkowski

## Description
Bugfix for picking (multi) images with PHPicker without gallery permissions.

While the current version allows accessing the gallery without permissions, it was still requiring them for returning picked images as a result. 

## Related issues
flutter/flutter#65995

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2022-09-15 12:11 UTC, stuartmorgan requested changes
Thanks for finding and fixing this! The code looks good, but the bug you are fixing needs test coverage (i.e., a test that would fail without the logic change).

2022-09-15 12:11 UTC, stuartmorgan commented on packages/image_picker/image_picker_ios/CHANGELOG.md
> +* Fixes issue with crashing the app when picking images with PHPicker without providing `Photo Library Usage` permission.
Nit: blank line above to match existing style please.

2022-09-17 00:35 UTC, jmagman commented on packages/image_picker/image_picker_ios/ios/Classes/FLTPHPickerSaveImageToPathOperation.m
> +  if (self.requestFullMetadata) {
How about a comment here like:
```suggestion
  // Only if requested, fetch the full "PHAsset" metadata, which requires  "Photo Library Usage" permissions.
  if (self.requestFullMetadata) {
```

2022-09-19 15:44 UTC, stuartmorgan approved these changes
LGTM

2022-09-19 19:03 UTC, jmagman approved these changes
LGTM

2022-09-19 19:05 UTC, merged

2022-10-21 07:37 UTC, liumengchun commented
Hello, have you fixed the problem of 'Select More Photos'? I have also reproduced the problem here