[video_player] Add embedded cc support for video player
flutter/plugins pull request #6817
Opened 2022-12-09 11:59 UTC by mahdishahbazi3653

Some videos like HLS includes embedded subtitle in them self. Both mobile native players (Exoplayer and AVPlayer) supports this functionality. 
User now can get available subtitle option and set one of it. The video_player will stream subtitle from native to flutter video_player controller caption so we can show in flutter.

Fixed issues:
- https://github.com/flutter/flutter/issues/109153
- https://github.com/flutter/flutter/issues/50595

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

2022-12-09 13:24 UTC, mahdishahbazi3653 commented
Closing PR Since build fails. Will send separate PR for interface, Android, iOS and video player it self

2022-12-09 18:45 UTC, stuartmorgan commented
Please see https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins for our process for multi-package changes.

2022-12-12 21:16 UTC, hellohuanlin commented
Hmmm, this work could be skipped if we migrate to platform view implementation sooner (which supports CC out of the box). 

As of now we have no choice but to manually add CC labels. I saw you pushed updates. Let me know if it's ready for review.

2022-12-22 10:03 UTC, mahdishahbazi3653 commented
@hellohuanlin The PR is ready for review now.

2023-01-10 05:42 UTC, hellohuanlin requested changes
Thanks for your contribution. I reviewed the iOS part. 

Can you share a gif/video of how it works in PR description?

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player/CHANGELOG.md
> +* Added support Embedded Close Caption with videos
*Adds* support *for* embedded close caption with videos.

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player/example/lib/main.dart
> +                        'https://mtoczko.github.io/hls-test-streams/test-vtt-fmp4-segments/playlist.m3u8',
can you use flutter website to host those assets? (you can find examples in this file

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player/example/lib/main.dart
> +    _controller.initialize().then((_) => setupSubtitle());
should "setupSubtitle" be part of the initialize function?

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player/example/lib/main.dart
> +    if (widget.useAssetCC) {
what's the difference between the `if` and `else` here? Is subtitle the same as CC?

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player/example/lib/main.dart
> +      await _controller.setEmbeddedSubtitles(subtitles.first);
Is it better to hide this subtitle list inside the controller?

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player/example/pubspec.yaml
> +# FOR TESTING ONLY. DO NOT MERGE.
Reminder to remove this.

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player/lib/video_player.dart
> +        EmbeddedSubtitle;
bad indentation?

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player_avfoundation/CHANGELOG.md
> +* Added support Embedded Close Caption with videos
same here

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player_avfoundation/example/ios/Flutter/AppFrameworkInfo.plist
> +  <string>11.0</string>
you probably don't want to check in these.

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player_avfoundation/example/ios/Runner/Info.plist
> +	<key>CADisableMinimumFrameDurationOnPhone</key>
is this intended?

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player_avfoundation/example/lib/main.dart
> +      'https://mtoczko.github.io/hls-test-streams/test-vtt-fmp4-segments/playlist.m3u8',
same comment here

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
> +@interface FLTVideoPlayer : NSObject <FlutterTexture, FlutterStreamHandler,AVPlayerItemLegibleOutputPushDelegate>
space

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
> +    for(int i=0;i<[characteristics count];i++){
`.count`

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
> +                                                         renderIndex:@(2)];
What does render index = 2 mean? can you comment about this magic number?

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
> +    return subtitles;
can directly return here. Also why are you returning an empty mutable array here?

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
> +            inMediaSelectionGroup:group
format

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
> +            @"value" : @"",
why is it empty string here?

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
> +@property(nonatomic, readonly) NSNumber* textTrackIndex;
this can probably be just NSInteger, since index can't be floating point.

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
> +        AVMediaCharacteristic characteristic = characteristics[i];
you can use `enumerateObjectsUsingBlock` to access both index and the element itself

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
> +        if([characteristic.description isEqual: @"AVMediaCharacteristicLegible"]){
for string comparison, you should use `isEqualToString:`

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
> +            ];
format

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
> +            NSArray<AVMediaSelectionOption *> *options = [group options];
.options

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
> +        AVMediaCharacteristic characteristic = characteristics[[groupIndex intValue]];
do we need to watch out for index out of bounds?

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
> +            NSAttributedString *string = [strings firstObject];
duplicate

2023-01-10 05:42 UTC, hellohuanlin commented on packages/video_player/video_player_avfoundation/ios/Classes/FLTVideoPlayerPlugin.m
> +    return [player getEmbeddedSubtitles];
do we always use the first subtitle?

2023-01-23 18:47 UTC, camsim99 reviewed
Reviewed the Android components! Looks good overall, but some Java tests should be added for the changes.

2023-01-23 18:47 UTC, camsim99 commented on packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
> +    int rendererIndex = 2;
It is my understanding that `C.TRACK_TYPE_VIDEO` [maps to 2](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/C.html#TRACK_TYPE_VIDEO), which is why you are using it here. Can you use that constant for clarity?

2023-01-23 18:47 UTC, camsim99 commented on packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
> +    MappingTrackSelector.MappedTrackInfo trackInfo = trackSelector.getCurrentMappedTrackInfo();
I would suggest also ensuring here that `trackSelector` is not null like below in `setEmbeddedSubtitles()`.

2023-01-23 18:47 UTC, camsim99 commented on packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
> +        trackGroups = trackInfo.getTrackGroups(Math.toIntExact(rendererIndex));
To fix the failure, make sure to cast `Long` to `int` in a different way.

2023-01-23 18:47 UTC, camsim99 commented on packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
> +        parametersBuilder.setRendererDisabled(Math.toIntExact(rendererIndex), isDisabled);
Can't these two lines be done in one? Something like:
```
DefaultTrackSelector.Parameters.Builder parametersBuilder = 
    trackSelector
        .buildUponParameters()
        .setRendererDisabled(Math.toIntExact(rendererIndex), isDisabled);
```

2023-01-23 18:47 UTC, camsim99 commented on packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java
> +      eventSink.success(event);
Why is an event not added to the `eventSink` when embedded subtitles were successfully set? I assume it has something to do with going through `onCues()`, but I just wish to understand this decision better.

2023-02-09 20:59 UTC, stuartmorgan commented
@mahdishahbazi3653 Are you still planning on updating this PR to address the review comments above?

2023-02-10 08:18 UTC, mahdishahbazi3653 commented
@stuartmorgan Yes, I will take a look at them. A bit busy these days but will fix them ASAP

2023-02-22 15:52 UTC, stuartmorgan commented
We've just completed the migration of the plugin code to the flutter/packages repository, as described in https://flutter.dev/go/flutter-plugins-repo-migration, and this repository is now being archived. Unfortunately that means that all in-progress PRs here must be moved to flutter/packages.

Please see [our instructions](https://github.com/flutter/flutter/wiki/Migrating-Plugins-repository-PRs-to-Packages) for an explanation of how to move your PR, and if you have any issues moving your PR please don't hesitate to reach out in the #hackers-ecosystem channel in [Discord](https://github.com/flutter/flutter/wiki/Chat).

Our apologies that your PR was caught in this one-time transition. We're aware that it's disruptive in the short term, and appreciate your help in getting us to a better long-term state!

2023-02-22 15:52 UTC, closed without merging